name : first workflows

on :
   push:
     branches:
       - main 
jobs:
  example-job:
    runs-on: ubuntu-latest


    steps:
      - name: Print a welcome meassage
        run : echo "welcome to our frist github action workflows"

      - name : Checkout repository   
        uses: actions/checkout@v4.2.2

      - name : list repository files 
        run : ls -la
      
      

   
    
      
